<button onclick="location.href='/admin/autores/add'">
    Novo autor
</button>
<table>
    <thead>
    <th>Login</th><th>Perfil</th>
</thead>
<?php foreach ($autores as $autor) { ?>
    <tr>
        <td><?php  echo $autor['nome']; ?></td>
        <td><?php echo $autor['sobrenome']; ?></td>
        <td><a href="/admin/autores/update/id/<?php echo $autor['id_autor']; ?>" >Editar</a></td>
        <td><a href="/admin/autores/delete/id/<?php echo $autor['id_autor']; ?>" >Excluir</a></td>
    </tr>
<?php } ?>

</table>